[package]
name = "tlv320dac3100"
version = "0.1.0"
edition = "2024"

[dependencies]
embedded-hal = "1.0.0"

[dev-dependencies]
embedded-hal-mock = { version = "0.11.1", default-features = false, features = ["eh1"] }